[package]
name = "blake3"
version = "0.1.0"
authors = ["Connor Peet <connor@peet.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake3 = "0.1"
wasm-bindgen = "0.2"
js-sys = "0.3"
