on: [push]

name: CI

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - run: npm install --ci
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack
      - run: make MODE=debug
      - run: npm test
